/// Static keyword sets for the SQL autocomplete engine, grouped by the
/// clause / statement slot they belong to. Pure data — the completers
/// pick a list and the ranker scores it against the typed token.
library;

const List<String> statementKeywords = [
  'SELECT',
  'INSERT INTO',
  'UPDATE',
  'DELETE FROM',
  'WITH',
  'CREATE',
  'ALTER',
  'DROP',
  'TRUNCATE',
  'EXPLAIN',
];

const List<String> selectListKeywords = [
  'DISTINCT',
  'ALL',
  'AS',
  'CASE',
  'WHEN',
  'THEN',
  'ELSE',
  'END',
  'COUNT(*)',
  'NULL',
  'TRUE',
  'FALSE',
  'FROM',
];

const List<String> selectTailKeywords = [
  'WHERE',
  'GROUP BY',
  'ORDER BY',
  'HAVING',
  'LIMIT',
  'OFFSET',
  'JOIN',
  'INNER JOIN',
  'LEFT JOIN',
  'RIGHT JOIN',
  'FULL JOIN',
  'CROSS JOIN',
  'UNION',
  'INTERSECT',
  'EXCEPT',
];

const List<String> whereKeywords = [
  'AND',
  'OR',
  'NOT',
  'IS',
  'IS NULL',
  'IS NOT NULL',
  'IN',
  'BETWEEN',
  'LIKE',
  'ILIKE',
  'EXISTS',
  'ANY',
  'ALL',
  'NULL',
  'TRUE',
  'FALSE',
  'CASE',
  'WHEN',
  'THEN',
  'ELSE',
  'END',
];

const List<String> orderKeywords = [
  'ASC',
  'DESC',
  'NULLS FIRST',
  'NULLS LAST',
];

const List<String> joinTailKeywords = ['ON', 'USING', 'AS'];

// --- DML tails ----------------------------------------------------------

/// Keywords offered after `DELETE FROM <table>`.
const List<String> deleteTailKeywords = ['WHERE', 'USING', 'RETURNING'];

// --- DDL: object kinds --------------------------------------------------

const List<String> createObjectKeywords = [
  'TABLE',
  'TABLE IF NOT EXISTS',
  'TEMP TABLE',
  'UNLOGGED TABLE',
  'INDEX',
  'UNIQUE INDEX',
  'VIEW',
  'MATERIALIZED VIEW',
  'OR REPLACE VIEW',
  'SCHEMA',
  'SEQUENCE',
  'EXTENSION',
  'TYPE',
  'FUNCTION',
  'TRIGGER',
  'DATABASE',
  'ROLE',
];

const List<String> alterObjectKeywords = [
  'TABLE',
  'INDEX',
  'VIEW',
  'MATERIALIZED VIEW',
  'SEQUENCE',
  'SCHEMA',
  'TYPE',
  'DATABASE',
  'FUNCTION',
  'ROLE',
];

const List<String> dropObjectKeywords = [
  'TABLE',
  'TABLE IF EXISTS',
  'INDEX',
  'VIEW',
  'MATERIALIZED VIEW',
  'SEQUENCE',
  'SCHEMA',
  'TYPE',
  'EXTENSION',
  'TRIGGER',
  'FUNCTION',
  'DATABASE',
  'ROLE',
];

// --- DDL: ALTER TABLE actions ------------------------------------------

const List<String> alterTableActionKeywords = [
  'ADD COLUMN',
  'DROP COLUMN',
  'ALTER COLUMN',
  'RENAME COLUMN',
  'RENAME CONSTRAINT',
  'RENAME TO',
  'ADD CONSTRAINT',
  'DROP CONSTRAINT',
  'ADD PRIMARY KEY',
  'ADD FOREIGN KEY',
  'ADD UNIQUE',
  'ADD CHECK',
  'VALIDATE CONSTRAINT',
  'SET SCHEMA',
  'OWNER TO',
  'SET TABLESPACE',
  'ENABLE ROW LEVEL SECURITY',
  'DISABLE ROW LEVEL SECURITY',
  'INHERIT',
  'NO INHERIT',
];

const List<String> alterColumnActionKeywords = [
  'SET DEFAULT',
  'DROP DEFAULT',
  'SET NOT NULL',
  'DROP NOT NULL',
  'TYPE',
  'SET DATA TYPE',
  'ADD GENERATED ALWAYS AS IDENTITY',
  'DROP IDENTITY',
  'SET STATISTICS',
];

// --- DDL: constraints ---------------------------------------------------

const List<String> columnConstraintKeywords = [
  'PRIMARY KEY',
  'NOT NULL',
  'NULL',
  'UNIQUE',
  'DEFAULT',
  'REFERENCES',
  'CHECK',
  'GENERATED ALWAYS AS IDENTITY',
  'GENERATED BY DEFAULT AS IDENTITY',
  'COLLATE',
];

const List<String> tableConstraintKeywords = [
  'PRIMARY KEY',
  'FOREIGN KEY',
  'UNIQUE',
  'CHECK',
  'CONSTRAINT',
  'EXCLUDE',
  'LIKE',
];

/// Lowercased first words of [tableConstraintKeywords] — lets the
/// column-definition matcher tell a table-constraint line apart from a
/// plain `<column> <type>` definition.
const Set<String> tableConstraintStartWords = {
  'primary',
  'foreign',
  'unique',
  'check',
  'constraint',
  'exclude',
  'like',
};

// --- DDL: data types ----------------------------------------------------

/// Built-in types offered in column-definition / `ALTER COLUMN … TYPE`
/// slots. Lowercase to match the project's data-identifier convention;
/// user-defined enum/domain types are appended at completion time.
const List<String> dataTypeKeywords = [
  'bigint',
  'bigserial',
  'boolean',
  'bytea',
  'blob',
  'char',
  'character varying',
  'cidr',
  'date',
  'double precision',
  'inet',
  'integer',
  'interval',
  'json',
  'jsonb',
  'macaddr',
  'money',
  'numeric',
  'real',
  'serial',
  'smallint',
  'smallserial',
  'text',
  'time',
  'timestamp',
  'timestamptz',
  'timestamp with time zone',
  'tsquery',
  'tsvector',
  'uuid',
  'varchar',
  'xml',
];

const List<String> indexMethodKeywords = [
  'btree',
  'hash',
  'gin',
  'gist',
  'spgist',
  'brin',
];

const List<String> truncateOptionKeywords = [
  'CASCADE',
  'RESTART IDENTITY',
  'CONTINUE IDENTITY',
  'RESTRICT',
];

const List<String> dropBehaviorKeywords = ['CASCADE', 'RESTRICT'];

// Re-exported for the clause-bar in table_view (single-line inputs).
const List<String> selectModifierKeywords = ['DISTINCT', 'AS', 'COUNT(*)'];

const List<String> whereOperatorKeywords = whereKeywords;

const List<String> orderModifierKeywords = orderKeywords;
